GET http://localhost:3000/profiles

###

Get https://randomuser.me/api/

###

POST http://localhost:3000/profiles
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "test",
    "age": "test",
    "country": "test",
    "city": "test",
    "president": "test",
}

###

DELETE http://localhost:3000/profiles/Price
